version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: preppulse_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: preppulse_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DB_NAME=preppulse
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: preppulse_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
